export default {
  // 文章
  START_GET_ARTICLE: 'START_GET-ARTICLE',
  GET_ARTICLE_SUCCESS: 'GET_ARTICLE_SUCCESS',
  DELETE_ARTICLE: 'DELETE_ARTICLE',
  GET_ARTICLE_READ_AMOUNT: 'GET_ARTICLE_READ_AMOUNT',
  // 通知
  MARK_NOTIFICATIONS_AS_READ_BY_ID: 'MARK_NOTIFICATIONS_AS_READ_BY_ID',
  MARK_ALL_AS_READ_BY_ID: 'MARK_ALL_AS_READ_BY_ID',
  START_NOTIFICATION_POST: 'START_NOTIFICATION_POST',
  FINISH_NOTIFICATION_POST: 'FINISH_NOTIFICATION_POST',
  RECEIVED_NOTIFICATIONS: 'RECEIVED_NOTIFICATIONS',
  // 用户
  START_LOGIN: 'START_LOGIN',
  SUCCESS_LOGIN: 'SUCCESS_LOGIN',
  FAILED_LOGIN: 'FAILED_LOGIN',
  CHANGE_AVATAR: 'changeAvatar',
  // 主题
  PETER_RIVER: 'PETER_RIVER',
  GREEN_SEA: 'GREEN_SEA',
  CARROT: 'CARROT',
  DEFAULT_COLOR: 'DEFAULT_COLOR',
}