export default {
  MARK_NOTIFICATIONS_AS_READ_BY_ID: 'MARK_NOTIFICATIONS_AS_READ_BY_ID',
  MARK_ALL_AS_READ_BY_ID: 'MARK_ALL_AS_READ_BY_ID',
  START_NOTIFICATION_POST: 'START_NOTIFICATION_POST',
  FINISH_NOTIFICATION_POST: 'FINISH_NOTIFICATION_POST',
  RECEIVED_NOTIFICATIONS: 'RECEIVED_NOTIFICATIONS',
  START_LOGIN:'START_LOGIN',
  SUCCESS_LOGIN:'SUCCESS_LOGIN',
  FAILED_LOGIN:'FAILED_LOGIN',
}